Yatik_Task4/Models/Center_Master.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Yatik_Task4.Models
{
    public class Center_Master
    {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }
    [StringLength(20)]
    //
    public string CenterName { get; set; }
    //public string CenterType { get; set; }
     public int SortOrder { get; set; }
    public bool IsActive { get; set; }
    }
}

Yatik_Task4/Models/EFCoreDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace Yatik_Task4.Models
{
    public class EFCoreDBContext:DbContext
    {
        public DbSet<Center_Master> Center_Masters { get; set; }
        public EFCoreDBContext(DbContextOptions<EFCoreDBContext> options): base(options)
        { }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
}

Yatik_Task4/Models/ErrorViewModel.cs
using System;

namespace Yatik_Task4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Yatik_Task4/Models/StudentMaster.cs
namespace Yatik_Task4.Models
{
    public class StudentMaster
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string City { get; set; }
    }
}

Yatik_Task4/Models/StudentModel.cs
namespace Yatik_Task4.Models
{
    public class StudentModel
    {
        public string Name { get; set; }     
        public string Address { get; set; }  
        public string Contact { get; set; }  
    }
}

Yatik_Task4/Controllers/CenterMasterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Yatik_Task4.Models;
using Yatik_Task4.DataRepository;

namespace Yatik_Task4.Controllers
{
    public class CenterMasterController: Controller
    {
        private readonly ICenterMasterRepository _ICenterMasterRepository;
        public CenterMasterController(ICenterMasterRepository centerMasterRepository)
        {
            _ICenterMasterRepository=centerMasterRepository;
        }
        public IActionResult UsingEF()
        {
            List<Center_Master> center_Master=new List<Center_Master>();
            center_Master=  _ICenterMasterRepository.GetCenterMasterData();
            ViewBag.cntcount = center_Master.Count();
            return View(center_Master);
        }
        public IActionResult UsingSP()
        {
            List<Center_Master> center_Master=new List<Center_Master>();
            center_Master= _ICenterMasterRepository.GetCenterMasterDataStoredProcedureWithCommon();
            return View(center_Master);
        }
        [HttpGet]
        public IActionResult CenterMasterEntry()
        {

            List<Center_Master> center_Master=new List<Center_Master>();
            
            center_Master= _ICenterMasterRepository.GetCenterMasterDataStoredProcedureWithCommon();
            return View(center_Master);
        }
        [HttpPost]
        public IActionResult CenterMasterEntry(Center_Master center_Master)
        {
            // List<Center_Master> center_Master=new List<Center_Master>();
            // center_Master= _ICenterMasterRepository.GetCenterMasterDataStoredProcedureWithCommon();
            return View(center_Master);
        }
    }
}

Yatik_Task4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Yatik_Task4.Models;
using Yatik_Task4.DataRepository;
using System.Data;

namespace Yatik_Task4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICenterMasterRepository _ICenterMasterRepository;
    
        public HomeController(ILogger<HomeController> logger,ICenterMasterRepository centerMasterRepository)
        {
            _logger = logger;
            _ICenterMasterRepository=centerMasterRepository;
        }

        public IActionResult Index()
        {
            List<Center_Master> center_Master=new List<Center_Master>();
            center_Master=  _ICenterMasterRepository.GetCenterMasterData();
            ViewBag.cntcount = center_Master.Count();
            return View(center_Master);
        }
        public IActionResult Privacy()
        {
            List<Center_Master> center_Master=new List<Center_Master>();
            center_Master= _ICenterMasterRepository.GetCenterMasterDataStoredProcedureWithCommon();
            return View(center_Master);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Yatik_Task4/Views/CenterMaster/CenterMasterEntry.cshtml
@model List<Center_Master>


@{
    ViewData["Title"] = "Center Master Entry";
}
 <h1>Center Master Entry</h1>

Yatik_Task4/Views/CenterMaster/UsingEF.cshtml
@model List<Center_Master>


@{
    ViewData["Title"] = "Home Page";
}
 <h1>Using EF</h1>
<div class="text-center">
    Total Records @ViewBag.cntcount
    <table class="table table-border">
    <thead class="thead-dark">
     <tr>
         <th>Center Name</th>
         <th>Sort </th>
         <th>Is Active</th>
     </tr>
    </thead>
@foreach(var Master in Model)
   {
    <tr>
        <td>@Master.CenterName</td>
        <td>@Master.SortOrder</td>
         <td>@(Master.IsActive? "Yes" : "No")</td>
        
    </tr>
   }
</table>
</div>

Yatik_Task4/Views/CenterMaster/UsingSP.cshtml
@model List<Center_Master>
 <h1>Using SP</h1>
<div class="text-center">
    Total Records @ViewBag.cntcount
    <table class="table table-border">
     <tr>
         <th>Center Id</th>
         <th>Center Name</th>
         <th>Sort </th>
         <th>Is Active</th>
     </tr>
 
@foreach(var Master in Model)
   {
    <tr>
        <td>@Master.ID</td>
        <td>@Master.CenterName</td>
        <td>@Master.SortOrder</td>
        @if(Master.IsActive)
        {
            <td>Yes</td>
        }
        else
        {
            <td>No</td>
        }
    </tr>
   }
</table>
</div>

Yatik_Task4/Views/Home/Index.cshtml
@model List<Center_Master>


@{
    ViewData["Title"] = "Home Page";
}
 
<div class="text-center">
    Total Records @ViewBag.cntcount
    <table class="table table-border">
     <tr>
         <th>Center Id</th>
         <th>Center Name</th>
         <th>Sort </th>
         <th>Is Active</th>
     </tr>
 
@foreach(var Master in Model)
   {
    <tr>
        <td>@Master.ID</td>
        <td>@Master.CenterName</td>
        <td>@Master.SortOrder</td>
        @if(Master.IsActive==true)
        {
            <td>Yes</td>
        }
        else
        {
            <td>No</td>
        }
    </tr>
   }
</table>
</div>

Yatik_Task4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CenterMaster" asp-action="UsingEF">EF </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CenterMaster" asp-action="UsingSP">Stored Procedure</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Yatik_Task4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>